### ISSUE TITLE
Cant stop SSL 

### ISSUE THREAD

**Issue by aleksandrov89** [ugjka/newyearsbot#13]
Can't stop using SSL with command -ssl in prebuild package. Need to MAKE with source code to work without SSL.

**Comment by ugjka** [comment]
did you pass `-ssl=false` ?

**Comment by aleksandrov89** [comment]
i try with -ssl "false" as was written in information ? Need -ssl=false to work ?

**Comment by ugjka** [comment]
Yeah it seems you need -ssl=false

**Comment by aleksandrov89** [comment]
Yes with -ssl=false its working thanks. But i think its better to write in example config to avoid using -ssl "false" as i am using for channels and etc.

**Comment by ugjka** [comment]
I replaced the `-ssl` by its inverse `-nossl`. Now to disable ssl you just pass `-nossl`

**Comment by aleksandrov89** [comment]
Yes, it's much easier that way and you can't go wrong like I did.

**Comment by ugjka** [comment]
4c9eddfe12aec4f0ba0690341a60da327b278756 fixes the issue, closing... :)
