### ISSUE TITLE
Support for multiple server connections

### ISSUE THREAD

**Issue by TehPeGaSuS** [ugjka/newyearsbot#14]
Just wondering if multi-server connections will be supported on a near future.

Something like: `./newyearsbot -nick HNY_Bot -email bots@example.com -server irc.example.com:6697 -password "password" -channels "#channel1, #channel2"; -nick HNY_Bot -email bots@example.com -server localhost:1334 -password "password" -channels "#channel1, #channel2"`

Some food for thoughts, only.

**Comment by ugjka** [comment]
I think my idea is that i will support loading a config from Yaml file or something like that instead of doing crazy thing with cli flags

**Comment by PeGaSuS-Coder** [comment]
That work for me!

I like the type of configuration of things like Matterbridge, i.e.

**Comment by ugjka** [comment]
See https://github.com/ugjka/newyearsbot/blob/master/settings.yaml
